spring:
  profiles:
    active: local
    include: oauth

  datasource:
    url: jdbc:h2:tcp://localhost/~/webservice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  #datasource:
  #  url: webservice.c7lmmj1i3i2l.ap-northeast-2.rds.amazonaws.com
  #  username: hugebird
   # password: 5ab5c87a
  #  driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
  session:
    jdbc:
      initialize-schema: always
    store-type: jdbc
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace